# Generated by Django 4.0.1 on 2022-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyaccount', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyaccount',
            name='details',
        ),
        migrations.AddField(
            model_name='moneyaccount',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('savings', 'Savings'), ('investing', 'Investing'), ('other', 'Other')], default='personal', max_length=50),
        ),
    ]
