# Generated by Django 4.0.1 on 2022-02-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyaccount', '0005_remove_moneyaccount_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('deposit', 'Deposit')], default='payment', max_length=50),
        ),
    ]
