# Generated by Django 4.0.1 on 2022-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyaccount', '0006_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('deposit', 'Deposit')], max_length=50),
        ),
    ]
